packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - '@tailwindcss/oxide'
  - bufferutil
  - keccak
  - prisma
  - secp256k1
  - sharp
  - unrs-resolver
  - utf-8-validate
